import com.electronwill.nightconfig.core.serde.annotations.SerdeSkipDeserializingIf
import org.apache.tools.ant.filters.ReplaceTokens
import work.lclpnet.build.task.GithubDeploymentTask
import work.lclpnet.kibu.config.ConfigManager

import static com.electronwill.nightconfig.core.serde.annotations.SerdeSkipDeserializingIf.SkipDeIf.IS_MISSING

buildscript {
    dependencies {
        classpath "work.lclpnet.mods.kibu:kibu-config-api:0.1.1"
    }
}

plugins {
    alias(libs.plugins.java)
    alias(libs.plugins.fabric.loom) apply false
    alias(libs.plugins.maven.publish)
    alias(libs.plugins.gradle.build.utils)
    alias(libs.plugins.lombok) apply false
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.kotlin.lombok)
}

Properties props = buildUtils.loadProperties("publish.properties")

group = project.maven_group
version = "${project.mod_version}+${libs.versions.minecraft.get()}"

def modId = project.mod_id
def javaVersion = libs.versions.java.get().toInteger()

base {
    archivesName = modId
}

allprojects {
    apply(plugin: libs.plugins.fabric.loom.get().pluginId)
    apply(plugin: libs.plugins.lombok.get().pluginId)
    apply(plugin: libs.plugins.kotlin.serialization.get().pluginId)

    repositories {
        mavenCentral()

        maven {
            url "https://repo.lclpnet.work/repository/internal"
        }

        maven {
            url "https://repo.lclpnet.work/repository/snapshots"
        }

        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
                }
            }
            filter {
                includeGroup "maven.modrinth"
            }
        }

        maven {
            url = "https://maven.nucleoid.xyz/"
        }

//    mavenLocal()
    }

    // common dependencies
    dependencies {
        minecraft(libs.minecraft)
        implementation(libs.fabric.loader)
        implementation(libs.fabric.api)

        implementation(libs.kibu)
        implementation(libs.kibu.world.api)
        implementation(libs.kibu.physics)
        implementation(libs.fantasy)
        implementation(libs.combat.control)
        implementation(libs.notica)
        implementation(libs.mg.lobby)
        implementation(libs.pal)
        implementation(libs.gaco)
        implementation(libs.game.map.api)
        implementation(libs.map.canvas.api)

        implementation(libs.json)
        compileOnly(libs.jetbrains.annotations)
        implementation(libs.ktor.serialization.kotlinx.json)

        testImplementation(libs.junit.jupiter.api)
        testRuntimeOnly(libs.junit.jupiter.engine)
        testImplementation(libs.junit.jupiter.params)
        testImplementation(libs.fabric.loader.junit)
    }

    test {
        useJUnitPlatform()
        systemProperty("fabric.side", "server")
    }
}

subprojects {
    base {
        archivesName = "${rootProject.base.archivesName.get()}-${project.name}"
    }

    group = rootProject.maven_group
    version = rootProject.version
}

/*********************************************************************************************************************\
 * Source sets
 \*********************************************************************************************************************/
sourceSets {
    genResources {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
    }
}

static <C> C loadToml(File file, C config) {
    try (def manager = new ConfigManager<>(file.toPath(), config)) {
        manager.load()

        return manager.config()
    }
}

/*********************************************************************************************************************\
 * Dependencies
 \*********************************************************************************************************************/
dependencies {
    // extra dependencies required for compilation
    def includeImpl = { dep ->
        implementation(dep)
        include(dep)
    }

    include(libs.json.config4j)
    includeImpl(libs.commons.compress)
    includeImpl(libs.ktor.client.core)
    includeImpl(libs.ktor.client.cio)
    includeImpl(libs.ktor.client.content.negotiation)

    // ship ktor libraries for runtime use; should ideally be moved to separate library mod in the future
    include(libs.ktor.utils.jvm)
    include(libs.ktor.http.jvm)
    include(libs.ktor.client.cio.jvm)
    include(libs.ktor.io.jvm)
    include(libs.ktor.serialization.jvm)
    include(libs.ktor.network.jvm)
    include(libs.ktor.network.tls.jvm)
    include(libs.ktor.events.jvm)
    include(libs.ktor.serialization.kotlinx.jvm)
    include(libs.ktor.serialization.kotlinx.json)

    implementation(libs.fabric.language.kotlin)

    // runtime dependencies
    runtimeOnly(libs.modrinth.sqlite.jdbc)

    // optional runtime dependencies (not explicitly required for compilation, but needed to play the game)
    localRuntime(libs.ruler)
    localRuntime(libs.mcserver.api)

    // optional runtime dependencies (not required to play)
    localRuntime(libs.modrinth.anti.xray)
    localRuntime(libs.simple.ac)
    localRuntime(libs.toml4j)

    // test dependencies
    testImplementation(libs.junit.jupiter.api)
    testRuntimeOnly(libs.junit.jupiter.engine)
    testImplementation(libs.mockito.core)
    testImplementation(libs.junit.jupiter.params)
    testImplementation(libs.fabric.loader.junit)
    testImplementation(libs.sqlite.jdbc)
}

/*********************************************************************************************************************\
 * General
 \*********************************************************************************************************************/
loom {
    serverOnlyMinecraftJar()

    runs {
        remove client

        server {
            vmArgs "-Dfabric-tag-conventions-v2.missingTagTranslationWarning=SILENCED"
        }

        genResources {
            server()
            configName = "Generate Resources"
            source = sourceSets.genResources
        }
    }
}

/*********************************************************************************************************************\
 * Tasks
 \*********************************************************************************************************************/
tasks.withType(JavaCompile).configureEach {
    it.options.release.set(javaVersion)
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.toVersion(javaVersion)
    targetCompatibility = JavaVersion.toVersion(javaVersion)
}

kotlin {
    jvmToolchain(javaVersion)
}

// resource expansion
def configureResources(ProcessResources task) {
    def tokens = [
            "version": project.version.toString(),
            "fantasy_version": libs.versions.fantasy.get(),
            "loader_version": libs.versions.fabric.loader.get(),
            "minecraft_compat": project.minecraft_compat,
            "java_version": libs.versions.java.get()
    ]

    task.inputs.properties(tokens)

    task.filesMatching("fabric.mod.json") {
        expand(tokens)
    }

    task.filesMatching("*.mixins.json") {
        filter(ReplaceTokens, beginToken: '${', endToken: '}', tokens: tokens)
    }
}

configureResources(processResources)

def licenseJarTasks = [jar, sourcesJar]

// rename LICENSE files
licenseJarTasks.each {
    it.from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}

dependencies {
    subprojects.each {
        api(it)
    }
}

// add extra source set remapped artifacts to main jar output
configurations {
    nestedJars {
        transitive = false
    }
}

dependencies {
    subprojects.each {
        nestedJars(project("${it.path}"))
    }
}

loom.nestJars(tasks.named("jar"), configurations.nestedJars)

/*********************************************************************************************************************\
 * Publishing
 \*********************************************************************************************************************/
def env = System.getenv()

tasks.register("github", GithubDeploymentTask) {
    dependsOn tasks.jar

    config {
        token = env.get("GITHUB_TOKEN")
        repository = env.get("GITHUB_REPOSITORY")
    }

    release {
        title = "[${libs.versions.minecraft.get()}] $project.name $project.version"
        tag = project.version
    }

    assets.add(tasks.jar.archiveFile.get())
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = project.base.archivesName.get()

            from components.java

            pom {
                name = "Arcade Party 2"
                description = "Reworked ArcadeParty as Fabric mini-game."
            }
        }
    }

    buildUtils.setupPublishRepository(repositories, props)
}