import com.electronwill.nightconfig.core.serde.annotations.SerdeSkipDeserializingIf
import org.apache.tools.ant.filters.ReplaceTokens
import work.lclpnet.build.task.GithubDeploymentTask
import work.lclpnet.kibu.config.ConfigManager

import static com.electronwill.nightconfig.core.serde.annotations.SerdeSkipDeserializingIf.SkipDeIf.IS_MISSING

buildscript {
    dependencies {
        classpath "work.lclpnet.mods.kibu:kibu-config-api:0.1.1"
    }
}

plugins {
    alias(libs.plugins.java)
    alias(libs.plugins.fabric.loom)
    alias(libs.plugins.maven.publish)
    alias(libs.plugins.gradle.build.utils)
    alias(libs.plugins.lombok)
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.kotlin.lombok)
}

Properties props = buildUtils.loadProperties("publish.properties")

group = project.maven_group
version = "${project.mod_version}+${libs.versions.minecraft.get()}"

def modId = project.mod_id
def javaVersion = libs.versions.java.get().toInteger()

base {
    archivesName = modId
}

/*********************************************************************************************************************\
 * Repositories
 \*********************************************************************************************************************/
repositories {
    mavenCentral()

    maven {
        url "https://repo.lclpnet.work/repository/internal"
    }

    maven {
        url "https://repo.lclpnet.work/repository/snapshots"
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }

    maven {
        url = "https://maven.nucleoid.xyz/"
    }

    maven {
        url "https://maven.terraformersmc.com/releases/"
    }

    maven {
        url "https://maven.shedaniel.me/"
    }

//    mavenLocal()
}

/*********************************************************************************************************************\
 * Source sets
 \*********************************************************************************************************************/
sourceSets {
    lib {
        // contains commonly used utilities among minigames and variants
    }

    main {
        compileClasspath += lib.output
        runtimeClasspath += lib.output
    }

    test {
        compileClasspath += lib.output
        runtimeClasspath += lib.output
    }

    genResources {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
    }
}

static <C> C loadToml(File file, C config) {
    try (def manager = new ConfigManager<>(file.toPath(), config)) {
        manager.load()

        return manager.config()
    }
}

// extra source sets will have all dependencies of the main source set, as well as their own jar artifact
def extraSourceSets = ['lib']

// configure modes
class Mode {
    String id
}

class ModesConfig {
    List<Mode> modes = []
}

def modesConfig = loadToml(file("src/modes/modes.toml"), new ModesConfig())

modesConfig.modes.each { mode ->
    extraSourceSets.add(mode.id)

    sourceSets.register(mode.id) { set ->
        resources.srcDirs = ["src/modes/${mode.id}/resources"]

        java.srcDirs = ["src/modes/${mode.id}/java"]

        compileClasspath += sourceSets.lib.output
        runtimeClasspath += sourceSets.lib.output

        sourceSets.main.runtimeClasspath += set.output
        sourceSets.test.compileClasspath += set.output
        sourceSets.test.runtimeClasspath += set.output
    }
}

// configure minigames
class Minigame {
    String id

    @SerdeSkipDeserializingIf([IS_MISSING])
    List<String> type = ["java"]

    @SerdeSkipDeserializingIf([IS_MISSING])
    boolean enabled = true
}

class MinigamesConfig {
    List<Minigame> minigames = []
}

def minigamesConfig = loadToml(file("src/minigames/minigames.toml"), new MinigamesConfig())

minigamesConfig.minigames.each { minigame ->
    if (!minigame.enabled) return

    extraSourceSets.add(minigame.id)

    sourceSets.register(minigame.id) {set ->
        resources.srcDirs = ["src/minigames/${minigame.id}/resources"]

        minigame.type.each { type ->
            set."$type".srcDirs = ["src/minigames/${minigame.id}/$type"]
        }

        compileClasspath += sourceSets.lib.output
        runtimeClasspath += sourceSets.lib.output

        sourceSets.main.runtimeClasspath += set.output
        sourceSets.genResources.runtimeClasspath += set.output
        sourceSets.test.compileClasspath += set.output
        sourceSets.test.runtimeClasspath += set.output
    }
}

// extra source sets need to have the necessary dependencies (atm inherit all; maybe cleanup in the future)
afterEvaluate {
    configurations {
        extraSourceSets.each {
            named("${it}Implementation").get().extendsFrom(implementation)
            named("${it}CompileOnly").get().extendsFrom(compileOnly)
            named("${it}CompileClasspath").get().extendsFrom(modCompileClasspathMapped)
            named("${it}RuntimeClasspath").get().extendsFrom(modRuntimeClasspathMapped)
            named("${it}CompileClasspath").get().extendsFrom(minecraftNamedCompile)
            named("${it}RuntimeClasspath").get().extendsFrom(minecraftNamedRuntime)
        }
    }
}

/*********************************************************************************************************************\
 * Dependencies
 \*********************************************************************************************************************/
dependencies {
    minecraft(libs.minecraft)
    implementation(libs.fabric.loader)
    implementation(libs.fabric.api)

    // extra dependencies required for compilation
    implementation(libs.json)
    compileOnly(libs.jetbrains.annotations)

    def includeImpl = { dep ->
        implementation(dep)
        include(dep)
    }

    includeImpl(libs.json.config4j)
    includeImpl(libs.commons.compress)
    includeImpl(libs.ktor.client.core)
    includeImpl(libs.ktor.client.cio)
    includeImpl(libs.ktor.client.content.negotiation)
    includeImpl(libs.ktor.serialization.kotlinx.json)

    include(libs.ktor.utils.jvm)
    include(libs.ktor.http.jvm)
    include(libs.ktor.client.cio.jvm)
    include(libs.ktor.io.jvm)
    include(libs.ktor.serialization.jvm)
    include(libs.ktor.network.jvm)
    include(libs.ktor.network.tls.jvm)
    include(libs.ktor.events.jvm)
    include(libs.ktor.serialization.kotlinx.jvm)

    implementation(libs.kibu)
    implementation(libs.kibu.world.api)
    implementation(libs.kibu.physics)
    implementation(libs.fantasy)
    implementation(libs.combat.control)
    implementation(libs.notica)
    implementation(libs.mg.lobby)
    implementation(libs.fabric.language.kotlin)
    implementation(libs.pal)
    implementation(libs.gaco)
    implementation(libs.game.map.api)
    implementation(libs.map.canvas.api)

    // runtime dependencies
    runtimeOnly(libs.modrinth.sqlite.jdbc)

    // optional runtime dependencies (not explicitly required for compilation, but needed to play the game)
    localRuntime(libs.ruler)
    localRuntime(libs.mcserver.api)
    implementation(libs.translations4j)
    implementation(variantOf(libs.translations4j) { classifier('network') })

    // optional runtime dependencies (not required to play)
    localRuntime(libs.modrinth.anti.xray)
    localRuntime(libs.simple.ac)
    localRuntime(libs.toml4j)

    // test dependencies
    testImplementation(libs.junit.jupiter.api)
    testRuntimeOnly(libs.junit.jupiter.engine)
    testImplementation(libs.mockito.core)
    testImplementation(libs.junit.jupiter.params)
    testImplementation(libs.fabric.loader.junit)
    testImplementation(libs.sqlite.jdbc)
}

/*********************************************************************************************************************\
 * General
 \*********************************************************************************************************************/
loom {
    serverOnlyMinecraftJar()

    runs {
        remove client

        server {
            vmArgs "-Dfabric-tag-conventions-v2.missingTagTranslationWarning=SILENCED"
        }

        genResources {
            server()
            configName = "Generate Resources"
            source = sourceSets.genResources
        }
    }

    accessWidenerPath = file("src/lib/resources/ap2.accesswidener")
}

test {
    useJUnitPlatform()
    systemProperty("fabric.side", "server")
}

/*********************************************************************************************************************\
 * Tasks
 \*********************************************************************************************************************/
tasks.withType(JavaCompile).configureEach {
    it.options.release.set(javaVersion)
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.toVersion(javaVersion)
    targetCompatibility = JavaVersion.toVersion(javaVersion)
}

kotlin {
    jvmToolchain(javaVersion)
}

// resource expansion
def configureResources(ProcessResources task) {
    def tokens = [
            "version": project.version.toString(),
            "fantasy_version": libs.versions.fantasy.get(),
            "loader_version": libs.versions.fabric.loader.get(),
            "minecraft_compat": project.minecraft_compat,
            "java_version": libs.versions.java.get()
    ]

    task.inputs.properties(tokens)

    task.filesMatching("fabric.mod.json") {
        expand(tokens)
    }

    task.filesMatching("*.mixins.json") {
        filter(ReplaceTokens, beginToken: '${', endToken: '}', tokens: tokens)
    }
}

configureResources(processResources)

extraSourceSets.each { name ->
    def task = tasks.named("process${name.capitalize()}Resources", ProcessResources).get()
    configureResources(task)
}

def licenseJarTasks = [jar, sourcesJar]

// add jar and remapJar tasks for extra source Sets
Jar prevJarTask = null

for (name in extraSourceSets) {
    // add extra jar task
    def jar = tasks.register("${name}Jar", Jar.class) {
        from(sourceSets.named(name).get().output)
        archiveClassifier.set(name)

        description "Builds the standalone ${name} api jar."
        group 'build'
    }.get()

    if (prevJarTask != null) {
        jar.mustRunAfter(prevJarTask)
    }

    prevJarTask = jar

    tasks.assemble.dependsOn(jar)

    licenseJarTasks.add(jar)
}

// rename LICENSE files
licenseJarTasks.each {
    it.from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}

// add extra source set remapped artifacts to main jar output
configurations {
    nestedJars {
        transitive = false
    }
}

dependencies {
    extraSourceSets.each { name ->
        nestedJars(files(tasks.named("${name}Jar", Jar)))
    }
}

loom.nestJars(tasks.named("jar"), configurations.nestedJars)

/*********************************************************************************************************************\
 * Publishing
 \*********************************************************************************************************************/
def env = System.getenv()

tasks.register("github", GithubDeploymentTask) {
    dependsOn tasks.jar

    config {
        token = env.get("GITHUB_TOKEN")
        repository = env.get("GITHUB_REPOSITORY")
    }

    release {
        title = "[${libs.versions.minecraft.get()}] $project.name $project.version"
        tag = project.version
    }

    assets.add(tasks.jar.archiveFile.get())
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = project.base.archivesName.get()

            from components.java

            artifact libJar

            pom {
                name = "Arcade Party 2"
                description = "Reworked ArcadeParty as Fabric mini-game."
            }
        }
    }

    buildUtils.setupPublishRepository(repositories, props)
}