services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: arcade-party-2
    ports:
      - "25565:25565"
      - "24454:24454/udp"  # voice chat (optional)
    environment:
      EULA: true
      MAX_MEMORY: 6G
    restart: unless-stopped
    volumes:
      - ./run:/data