# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
loader_version=0.18.2
loom_version=1.15-SNAPSHOT
mod_version=0.1.0
minecraft_compat=1.21.11
java_version=21

# Plugin Properties
maven_group=work.lclpnet.mods
archives_base_name=arcade-party-2

# dependencies required for compilation
fabric_version=0.139.5+1.21.11
kibu_version=0.153.3+1.21.11
kibu_world_api_version=0.9.2+1.21.11
kibu_physics_version=0.2.0+1.21.11
fantasy_version=0.7.0+1.21.11
lobby_version=0.77.0+1.21.11
combat_control_version=1.11.0+1.21.11
notica_version=1.6.0+1.21.11
translations4j_version=2.11.0
kotlin_version=1.13.8+kotlin.2.3.0
pal_version=0.16.2+1.21.11
gaco_version=0.16.0+1.21.11
game_map_api_version=0.4.4+1.21.11
ktor_version=3.3.3
map_canvas_api_version=0.7.0+1.21.11

# dependencies not required for compilation, but required to play
mcserver_api_version=0.9.1+1.21.11
ruler_version=0.4.0+1.21.11

# truly optional dependencies
anti_xray_version=1.4.13+1.21.11
toml_version=0.7.2
simple_ac_version=0.2.0+1.21.11