# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Plugin Properties
maven_group=work.lclpnet.mods
mod_id=arcade-party-2
mod_version=0.1.0

minecraft_compat=26.1

# dependencies required for compilation
fabric_version=0.147.0+26.1.2
kibu_version=0.154.0+26.1
kibu_world_api_version=0.10.0+26.1.2
kibu_physics_version=0.2.0+26.1.2
lobby_version=0.78.0+26.1.2
combat_control_version=1.11.0+26.1.2
notica_version=2.0.0+26.1.2
translations4j_version=2.11.0
kotlin_version=1.13.11+kotlin.2.3.21
pal_version=0.16.2+26.1.2
gaco_version=0.16.0+26.1.2
game_map_api_version=0.4.4+26.1.2
ktor_version=3.3.3
map_canvas_api_version=0.8.0+26.1

# dependencies not required for compilation, but required to play
mcserver_api_version=0.9.1+26.1.2
ruler_version=0.4.0+26.1.2

# truly optional dependencies
anti_xray_version=fabric-1.4.16+26.1
toml_version=0.7.2
simple_ac_version=0.2.0+26.1.2