pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'LCLPNetwork Maven'
            url = 'https://repo.lclpnet.work/repository/internal'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "arcade-party-2"

include 'lib'
project(':lib').projectDir = file("src/lib")

def minigames = [
        "aim_master",
        "anvil_fall",
        "apocalypse_survival",
]

minigames.forEach {
    include(it)
    project(":$it").projectDir = file("src/minigames/$it")
}
