[versions]
minecraft = "26.2"
fabric-api = "0.152.2+26.2"
fabric-loader = "0.19.3"
fabric-loom = "1.17-SNAPSHOT"
gradle-build-tools = "1.8.0"
java = "25"
kotlin = "2.3.21"
lombok = "9.4.0"
fantasy = "0.8.2+26.2"
json = "20231013"
jetbrains-annotations = "26.0.2"
json-config4j = "1.0.0"
commons-compress = "1.26.2"
ktor = "3.3.3"
kibu = "0.159.0+26.2"
kibu-world-api = "0.10.0+26.2"
kibu-physics = "0.2.0+26.2"
mg-api = "0.8.0+26.2"
mg-lobby = "0.86.0+26.2"
combat-control = "1.12.0+26.2"
notica = "2.1.0+26.2"
fabric-language-kotlin = "1.13.11+kotlin.2.3.21"
pal = "0.16.2+26.2"
gaco = "0.16.0+26.2"
game-map-api = "0.4.4+26.2"
map-canvas-api = "0.9.0+26.2"
modrinth-sqlite-jdbc = "3.49.1.0+2025-07-12"
ruler = "0.4.0+26.2"
mcserver-api = "0.9.3+26.2"
translations4j = "2.11.0"
modrinth-anti-xray = "fabric-1.4.16+26.1"
simple-ac = "0.2.0+26.2"
toml4j = "0.7.2"
junit-jupiter = "5.8.1"
mockito = "5.23.0"
sqlite-jdbc = "3.41.2.2"
c2me = "0.4.1-alpha.0.3+26.2"
lithium = "mc26.2-0.25.0-fabric"
scalablelux = "0.2.1+fabric.2b08348"

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
maven-publish = { id = "maven-publish" }
java = { id = "java" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-lombok = { id = "org.jetbrains.kotlin.plugin.lombok", version.ref = "kotlin" }
gradle-build-utils = { id = "gradle-build-utils", version.ref = "gradle-build-tools" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-loader-junit = { module = "net.fabricmc:fabric-loader-junit", version.ref = "fabric-loader" }
fantasy = { module = "xyz.nucleoid:fantasy", version.ref = "fantasy" }
json = { module = "org.json:json", version.ref = "json" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
json-config4j = { module = "work.lclpnet:json-config4j", version.ref = "json-config4j" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-serialization-jvm = { module = "io.ktor:ktor-serialization-jvm", version.ref = "ktor" }
ktor-utils-jvm = { module = "io.ktor:ktor-utils-jvm", version.ref = "ktor" }
ktor-http-jvm = { module = "io.ktor:ktor-http-jvm", version.ref = "ktor" }
ktor-http-cio-jvm = { module = "io.ktor:ktor-http-cio-jvm", version.ref = "ktor" }
ktor-client-cio-jvm = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktor" }
ktor-io-jvm = { module = "io.ktor:ktor-io-jvm", version.ref = "ktor" }
ktor-network-jvm = { module = "io.ktor:ktor-network-jvm", version.ref = "ktor" }
ktor-network-tls-jvm = { module = "io.ktor:ktor-network-tls-jvm", version.ref = "ktor" }
ktor-events-jvm = { module = "io.ktor:ktor-events-jvm", version.ref = "ktor" }
ktor-serialization-kotlinx-jvm = { module = "io.ktor:ktor-serialization-kotlinx-jvm", version.ref = "ktor" }
kibu = { module = "work.lclpnet.mods.kibu:kibu", version.ref = "kibu" }
kibu-world-api = { module = "work.lclpnet.mods.kibu:kibu-world-api", version.ref = "kibu-world-api" }
kibu-physics = { module = "work.lclpnet.mods.kibu:kibu-physics", version.ref = "kibu-physics" }
mg-api = { module = "work.lclpnet.mods:mg-api", version.ref = "mg-api" }
mg-lobby = { module = "work.lclpnet.mods:mg-lobby", version.ref = "mg-lobby" }
combat-control = { module = "work.lclpnet.mods:combat-control", version.ref = "combat-control" }
notica = { module = "work.lclpnet.mods:notica", version.ref = "notica" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
pal = { module = "work.lclpnet.mods:pal", version.ref = "pal" }
gaco = { module = "work.lclpnet.mods.gaco:gaco", version.ref = "gaco" }
game-map-api = { module = "work.lclpnet.mods.gaco:game-map-api", version.ref = "game-map-api" }
map-canvas-api = { module = "eu.pb4:map-canvas-api", version.ref = "map-canvas-api" }
modrinth-sqlite-jdbc = { module = "maven.modrinth:minecraft-sqlite-jdbc", version.ref = "modrinth-sqlite-jdbc" }
ruler = { module = "work.lclpnet.mods:ruler", version.ref = "ruler" }
mcserver-api = { module = "work.lclpnet.mcserver-api:mcserver-api-fabric", version.ref = "mcserver-api" }
translations4j = { module = "work.lclpnet:translations4j", version.ref = "translations4j" }
modrinth-anti-xray = { module = "maven.modrinth:anti-xray", version.ref = "modrinth-anti-xray" }
simple-ac = { module = "work.lclpnet.mods:simple-ac", version.ref = "simple-ac" }
toml4j = { module = "com.moandjiezana.toml:toml4j", version.ref = "toml4j" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
c2me-fabric = { module = "maven.modrinth:c2me-fabric", version.ref = "c2me" }
lithium = { module = "maven.modrinth:lithium", version.ref = "lithium" }
scalablelux = { module = "maven.modrinth:scalablelux", version.ref = "scalablelux" }
