name = "arcade-party-2"
author = "LCLP"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2fd4b324be1e38d8468086549c0bf708bee05f68729cd211731178645572d12"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
