name = "arcade-party-2"
author = "LCLP"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1459bbd6458f6d5ae69d07673635784cdaa541d0ec701e8d1915b7394119908"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
