name = "arcade-party-2"
author = "LCLP"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f787f480f315b73bbf847c66425e7fb02f0629ca5d87e13023550a088b4aa954"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
