package work.lclpnet.ap2.game.aim_master

import net.minecraft.world.level.block.Block
import net.minecraft.world.level.block.Blocks.*
import work.lclpnet.gaco.ds.IndexedSet

class BlockOptions {
    fun getBlockOptions(): IndexedSet<Block> = IndexedSet<Block>().apply {
        add(OAK_WOOD)
        add(BIRCH_WOOD)
        add(MANGROVE_PLANKS)
        add(OAK_PLANKS)
        add(BAMBOO_BLOCK)
        add(MOSSY_COBBLESTONE)
        add(REINFORCED_DEEPSLATE)
        add(MUD_BRICKS)
        add(BRICKS)
        add(CHISELED_RED_SANDSTONE)
        add(NETHER_BRICKS)
        add(RED_NETHER_BRICKS)
        add(SEA_LANTERN)
        add(DARK_PRISMARINE)
        add(GILDED_BLACKSTONE)
        add(PURPUR_BLOCK)
        add(END_STONE)
        add(GOLD_BLOCK)
        add(DIAMOND_BLOCK)
        add(QUARTZ_BLOCK)
        add(WAXED_COPPER_BLOCK)
        add(WAXED_WEATHERED_COPPER)
        add(WAXED_OXIDIZED_COPPER)
        add(RED_WOOL)
        add(GREEN_WOOL)
        add(CYAN_CONCRETE)
        add(MAGENTA_CONCRETE)
        add(YELLOW_CONCRETE)
        add(MAGENTA_GLAZED_TERRACOTTA)
        add(WHITE_GLAZED_TERRACOTTA)
        add(BLACK_GLAZED_TERRACOTTA)
        add(TINTED_GLASS)
        add(MOSS_BLOCK)
        add(GRASS_BLOCK)
        add(PACKED_ICE)
        add(MAGMA_BLOCK)
        add(CRYING_OBSIDIAN)
        add(OBSIDIAN)
        add(SOUL_SOIL)
        add(EMERALD_ORE)
        add(NETHER_QUARTZ_ORE)
        add(ANCIENT_DEBRIS)
        add(RAW_IRON_BLOCK)
        add(RAW_GOLD_BLOCK)
        add(SHROOMLIGHT)
        add(WARPED_WART_BLOCK)
        add(RED_MUSHROOM_BLOCK)
        add(CHERRY_LEAVES)
        add(SPRUCE_LEAVES)
        add(FLOWERING_AZALEA_LEAVES)
        add(SLIME_BLOCK)
        add(DRIED_KELP_BLOCK)
        add(WET_SPONGE)
        add(MELON)
        add(JACK_O_LANTERN)
        add(BEEHIVE)
        add(HAY_BLOCK)
        add(PEARLESCENT_FROGLIGHT)
        add(SCULK)
        add(REDSTONE_LAMP)
        add(CRAFTING_TABLE)
        add(FLETCHING_TABLE)
        add(FURNACE)
        add(NOTE_BLOCK)
        add(BEACON)
        add(LODESTONE)
        add(BEE_NEST)
        add(BOOKSHELF)
        add(BARREL)
        add(RESPAWN_ANCHOR)
        add(CRAFTER)
        add(STICKY_PISTON)
        add(OBSERVER)
        add(TNT)
        add(TARGET)
        add(RESIN_BLOCK)
        add(CREAKING_HEART)
    }
}
